module.exports = {
    clearInputField: require('./clearInputField'),
    clickElement: require('./clickElement'),
    closeAllButFirstTab: require('./closeAllButFirstTab'),
    closeLastOpenedWindow: require('./closeLastOpenedWindow'),
    deleteCookie: require('./deleteCookie'),
    dragElement: require('./dragElement'),
    focusLastOpenedWindow: require('./focusLastOpenedWindow'),
    handleModal: require('./handleModal'),
    moveToElement: require('./moveToElement'),
    openWebsite: require('./openWebsite'),
    pause: require('./pause'),
    pressButton: require('./pressButton'),
    removeElement: require('./removeElement'),
    resizeScreenSize: require('./resizeScreenSize'),
    scroll: require('./scroll'),
    selectOption: require('./selectOption'),
    selectOptionByIndex: require('./selectOptionByIndex'),
    setCookie: require('./setCookie'),
    setInputField: require('./setInputField'),
    setPromptText: require('./setPromptText'),
    submitForm: require('./submitForm'),
    waitFor: require('./waitFor'),
    waitForVisible: require('./waitForVisible'),
    uploadFile: require('./uploadFile')
}
